global:
  backend: kokoro_onnx

moss_nano_onnx:
  init:
    model_root_dir: models/moss_nano_onnx
    device: cpu
    text_normalizer_type: wetext # none, legacy, wetext

  request:
    language: ZH_MIX_EN
    voice: Junhao
    speed: 1.0
    sample_rate: 48000
    audio_format: wav
    extras:
      prompt_text: ''
      prompt_audio_path: null

kokoro_onnx:
  init:
    model_root_dir: models/kokoro_onnx
    device: cpu
    text_normalizer_type: wetext # none, legacy, wetext

  request:
    language: ZH_MIX_EN
    voice: zf_001
    speed: 1.0
    sample_rate: 24000
    audio_format: wav
    extras:
      max_phoneme_length: 510

melo_onnx:
  init:
    model_root_dir: models/melotts_zh_mix_en_onnx
    device: cpu
    text_normalizer_type: wetext # none, legacy, wetext

  request:
    language: ZH_MIX_EN
    voice: zf_001
    speed: 1.0
    sample_rate: 44100
    audio_format: wav
    extras:
      sdp_ratio: 0.2
      noise_scale: 0.6
      noise_scale_w: 0.8
